name: Compile Linux Kernel

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04-arm

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Add build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper-compat libdw-dev libelf-dev

      - name: build kernel
        run: |
          ./build_kernel_deb.sh

      - uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: ${{ github.workspace }}/*.deb
